Use matplotlib coverage plot/genome diagram
onecodex/sars-cov-2 pull request #31
Opened 2021-04-20 00:17 UTC by christinehe

2021-04-20 00:34 UTC, audy requested changes
Two changes requested

2021-04-20 00:34 UTC, audy commented on Dockerfile
> +RUN npm install md5
Is this needed?

2021-04-20 00:34 UTC, audy commented on jobscript.sh
> +
This blank line breaks the jobscript

2021-04-20 00:39 UTC, audy commented on Dockerfile
> +    && apt-get autoclean \
is this needed?

2021-04-20 01:35 UTC, merged

2021-05-06 17:56 UTC, christinehe commented
BIO-277